### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by hldiniz** [stefjen07/ShadersNeuralNetwork#1]
Hi @stefjen07, first of all thanks for sharing this code. Where can I find the data sets? It doesn't seen to be included in the repo and I can't run your code.

**Comment by stefjen07** [comment]
Hi @hldiniz, thanks for your attention to the project.

You can run this algorithm on MNIST dataset without any problem (the algorithm downloads MNIST dataset automatically). But if you want to classify Hiragana, it may be a little tricky. I used Hiragana characters from ETL-8G dataset. Due to the terms of use I can't publish this dataset, but you can register [here](http://etlcdb.db.aist.go.jp/download-request), download ETL-8G, extract it with [an extractor](https://github.com/choo/etlcdb-image-extractor) and cook this dataset with a function included in this repo.
